name: Publish

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6
          bundler-cache: true

      - name: Publish version
        env:
          GEMFURY_API_TOKEN: ${{secrets.GEMFURY_API_TOKEN}}
          GEMFURY_SOURCE: ${{secrets.GEMFURY_SOURCE}}
        run: bin/publish_gem "omniauth-kit-oauth2.gemspec"
